mpi_head:
    build: .
    # image: openmpi
    ports: 
      - "22"
    links: 
      - mpi_node
    volumes:
      - ./mpi4py_benchmarks:/home/mpirun/mpi4py_benchmarks

mpi_node:
    build: .
    # image: openmpi
    volumes:
      - ./mpi4py_benchmarks:/home/mpirun/mpi4py_benchmarks

# version: "2"

# services:
#   mpi_head:
#     build: .
#     # image: openmpi
#     ports: 
#       - "22"
#     links: 
#       - mpi_node
#     networks:
#       - net

#   mpi_node:
#     build: .
#     # image: openmpi
#     networks:
#       - net

# networks:
#   net:
#     driver: bridge
